openapi: "3.0.0"
info:
  version: 1.0.0
  title: Tasks
  license:
    name: MIT
servers:
  - url: http://localhost/
paths:
  /tasks/{userId}:
    get:
      summary: List all tasks of a user
      tags:
        - tasks
      parameters:
        - name: userId
          in: path
          required: true
          description: The tasks related to a user-id
          schema:
            type: int
        - name: date
          in: query
          required: false
          description: The tasks for a certain date in YYYY-MM-DD format. It uses the current date if no date is provided.
          schema:
            type: string
      responses:
        '200':
          description: An array of tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tasks"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tasks/{id}/complete:
    put:
      summary: Complete a task
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          description: The task-id to be marked as completed
          schema:
            type: int
      responses:
        '200':
          description: The completed task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - task
        - date
        - completed
      properties:
        id:
          type: integer
          format: int32
        user_id:
          type: integer
          format: int32
        task:
          type: string
        date:
          type: string
          format: YYYY-MM-DD
        completed:
          type: string
          nullable: true
          format: YYYY-MM-DD HH:MM:SS
    Tasks:
      type: array
      items:
        $ref: "#/components/schemas/Task"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type: string
